//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecordsManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class PtntVaccineRecordsTable
    {
        public int PtntVacID { get; set; }
        public int VaccineID { get; set; }
        public string VacLotNumber { get; set; }
        public string Date1stDose { get; set; }
        public string Date2ndDose { get; set; }
    
        public virtual PtntInfoRecordsTable PtntInfoRecordsTable { get; set; }
        public virtual VaccineUnit VaccineUnit { get; set; }
    }
}
