//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecordsManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class PtntInfoRecordsTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PtntInfoRecordsTable()
        {
            this.PtntVaccineRecordsTables = new HashSet<PtntVaccineRecordsTable>();
        }
    
        public int PtntID { get; set; }
        public string PtntGivenName { get; set; }
        public string PtntMidName { get; set; }
        public string PtntSurname { get; set; }
        public Nullable<int> PtntAge { get; set; }
        public string PtntGender { get; set; }
        public Nullable<int> PtntWeight { get; set; }
        public string PtntBirthdate { get; set; }
        public string PtntBirthplace { get; set; }
        public string AddrHouseNum { get; set; }
        public string AddrSubdBrgy { get; set; }
        public string AddrCityProv { get; set; }
        public string FthrGivName { get; set; }
        public string FthrMidName { get; set; }
        public string FthrSurname { get; set; }
        public string MthrGivName { get; set; }
        public string MthrMidName { get; set; }
        public string MthrSurname { get; set; }
        public string GrdnGivName { get; set; }
        public string GrdnMidName { get; set; }
        public string GrdnSurname { get; set; }
        public string AgeUnit { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PtntVaccineRecordsTable> PtntVaccineRecordsTables { get; set; }
    }
}
