//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecordsManagementSystem
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PatientRecordsManagementSystemEntities : DbContext
    {
        public PatientRecordsManagementSystemEntities()
            : base("name=PatientRecordsManagementSystemEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<PtntInfoRecordsTable> PtntInfoRecordsTables { get; set; }
        public virtual DbSet<PtntVaccineRecordsTable> PtntVaccineRecordsTables { get; set; }
        public virtual DbSet<UsersTable> UsersTables { get; set; }
        public virtual DbSet<VaccineUnit> VaccineUnits { get; set; }
    }
}
