//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecordsManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class VaccineUnit
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VaccineUnit()
        {
            this.PtntVaccineRecordsTables = new HashSet<PtntVaccineRecordsTable>();
        }
    
        public int VaccineID { get; set; }
        public string VaccineName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PtntVaccineRecordsTable> PtntVaccineRecordsTables { get; set; }
    }
}
